section_1:
  years: [2012,2015,2018,2020]
section_2:
  topic_thres: 0.1
  rca_thres: 1.2
  trends_topic_value: 0.1
section_4:
  div_params:
    balance:
      - div_metric: hh
        method: binary
        threshold: 0.1
        sample: all
      - div_metric: hh
        method: max
        threshold: 
        sample: all
      - div_metric: entropy
        method: binary
        threshold: 0.1
        sample: all
    weitzman:
      - distance: cosine
        sample: all
      - distance: chebyshev
        sample: all
      - distance: jaccard
        sample: all
    rao_stirling: 
      - method: binary
        distance: cosine
        threshold: 0.1
        sample: all
      - method: binary
        distance: correlation
        threshold: 0.1
        sample: all
      - method: max
        distance: cosine
        threshold:
        sample: all
section_5:
  network_1:
    topic_threshold: 0.1
    y0: 2013
    y1: 2017
  network_2:
    topic_threshold: 0.1
    y0: 2019
    y1: 2021
  categories: ['cs.CV','cs.NE','cs.CL','cs.CR','cs.LG','stat.ML','cs.AI']
section_6:
  year: 2020
  threshold: 0.05
section_7:
  y0: 2018
  runs: 30
  sample_size: 1000
section_8:
  year_threshold: 2015
  paper_threshold: 75
  paper_year_threshold: 2018
  y0: 2018
  y1: 2020
  google_filter: True 
section_9:
  categories: ['cs.AI','cs.CL','cs.CV','cs.LG','cs.NE','stat.ML','cs.CY','cs.IR','cs.CR','cs.DC','cs.RO',
          'cs.SE']
  topic_highlights: [
    'optimizations_gpu_gpus_tensorflow_cpu',
    'items_recommendation_recommendations_item_recommender_systems','conversion_revenue_ads_click_advertising',
    'registration_medical_imaging_mri_scans_volumes',
    'adversarial_adversarial_examples_adversarial_training_adversarial_attacks_adversarial_perturbations',
    'security_iot_secure_protection_vulnerabilities',
    'code_source_code_bugs_apis_github','driving_vehicle_vehicles_autonomous_driving_road',
    'reinforcement_learning_deep_reinforcement_learning_model_free_q_learning_reinforcement_learning_algorithms',
    'recurrent_lstm_rnn_recurrent_neural_networks_rnns','swarm_pso_abc_particle_swarm_optimization_metaheuristic',
    'clinical_patients_medical_patient_healthcare',
    'law_society_legal_ethical_stakeholders','infection_pandemic_epidemic_infected_virus']
section_10:
  highlights_n: 50
  period: [2019,2020]
  activity_thresholds: [100,500,1000]